# Generated by Django 2.0.2 on 2018-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tw_cat',
            field=models.FloatField(max_length=200),
        ),
    ]
